name: Flask CI

on:
  push:
    branches: [main, master, feature/tests]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
        
      - name: Create virtual environment
        run: |
          python -m venv venv
          venv\scripts\activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Print debugging information
        run: |
          echo "Python Version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Contents of Working Directory: $(ls -1)"
          echo "Contents of site-packages: $(ls -1 venv/lib/python*)"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
        
      - name: Create virtual environment
        run: |
          python -m venv venv
          venv\scripts\activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run tests with pytest
        run: |
          python -m pytest tests/test_mock.py

      - name: Run tests unittest
        run: python -m unittest discover -s tests -p 'test_*.py'
  
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
        
      - name: Create virtual environment
        run: |
          python -m venv venv
          venv\scripts\activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Deploy to proudction
        uses: johnbeynon/render-deploy-action@0.0.8
        with:
          service-id: $({ secrest.SERVICE_ID })
          api-key: $({ secrests.RENDER_API_KEY })
  

